### PR TITLE
backport WITH_SOABI

### PR DESCRIPTION
**Pull request by maxbachmann**
@henryiii from my understanding this should be all thats required to backport `WITH_SOABI`.

### CODE REVIEW

**Comment by henryiii** [comment]
This looks correct to me.

**Comment by maxbachmann** [comment]
Now I only need to make releases with the fix in 4 projects ... :scream:

**Comment by henryiii** [comment]
FYI, I'm a fan of https://github.com/pybind/pybind11/blob/da8c730a62a7f9654433f5e2206bd1135a8b57d8/.pre-commit-config.yaml#L118-L125 to avoid random whitespace changes in cmake files. ;)

**Comment by henryiii** [comment]
Well, the pure python fallback helps in some of them - maybe only rush out the releases in the ones where there's no fallback first.

**Comment by maxbachmann** [comment]
Yeah I still did not get started with pre-commit in my repositories. Should really get to it

**Comment by henryiii** [comment]
My page on it: https://scikit-hep.org/developer/style (though it is missing the cmake-format one due to it not being required much of the time - likely will be added as we start integrating scikit-build a bit more).

**Comment by maxbachmann** [comment]
> Well, the pure python fallback helps in some of them

Yes, but that is a lot slower :)
Still makes sense to start here, since the rapidfuzz ci easily takes 2-3 hours to make a release

**Pull request merged**
